/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_manus_JavaSerialLib */

#ifndef _Included_com_manus_JavaSerialLib
#define _Included_com_manus_JavaSerialLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_manus_JavaSerialLib
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_manus_JavaSerialLib_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_manus_JavaSerialLib
 * Method:    init
 * Signature: (Ljava/lang/String;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_manus_JavaSerialLib_init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_manus_JavaSerialLib
 * Method:    connect
 * Signature: (Ljava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_manus_JavaSerialLib_connect
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_manus_JavaSerialLib
 * Method:    write
 * Signature: (Ljava/nio/ByteBuffer;[BI)Z
 */
JNIEXPORT jint JNICALL Java_com_manus_JavaSerialLib_write
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     com_manus_JavaSerialLib
 * Method:    read
 * Signature: (Ljava/nio/ByteBuffer;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_manus_JavaSerialLib_read
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
